### ISSUE TITLE
Initial scroll to position

### ISSUE THREAD

**Issue by jasonkaruza** [ariedov/flutter_snaplist#17]
First, thank you for this awesome plugin. Looking forward to using it.

Because there is no controller accepted as a parameter to the SnapList constructor, there is no way to facilitate starting at an initial index, or scrolling to a particular index. It would be wonderful if such functionality could be added.

**Comment by ariedov** [comment]
@jasonkaruza Thanks, that is a great suggestion!

**Comment by ariedov** [comment]
Check out the version 0.1.8, there is a `SnaplistController` with an initial position in it and setting a position programmatically.

**Comment by jasonkaruza** [comment]
Many thanks! It might be useful to add a comment indicating if position is 0-based or 1-based as the starting position index. You guys rock!
