### ISSUE TITLE
Hot reload issues 

### ISSUE THREAD

**Issue by ariedov** [ariedov/flutter_snaplist#7]
When changing a parameter on the Snaplist itself the app has to be restarted to apply changes.

**Comment by raacker** [comment]
What was the issue?

**Comment by ariedov** [comment]
Updated the description. 

For instance: the axis change is not applied until the app restart. Does not work by hot reload.

**Comment by raacker** [comment]
Figured out and fixed. But want to ask first, Bloc is currently initialize at SnapList creation (initState) using final fields including sizeProvider, separatorProviders, etc. But if we want to support runtime build and changes to get hot-reload advantage, we should shrink them into fields. Would it be okay to you?

**Comment by ariedov** [comment]
Yes, it will be totally ok. Thank you!

**Comment by ariedov** [comment]
Just don't forget to update on `didUpdateWidget`.

**Comment by raacker** [comment]
Yup :)

**Comment by raacker** [comment]
@ariedov hmm... seems I got a problem with keeping start position. So, when we do hot reload the app, the center position is still on previous center. But that leads to make all center positions to off from center since it's not correctly calculated. Why don't we reset the progress when it does reload? I was keep testing on make it to move proper position but I think just resetting all stuffs would be safe and stable in any situations :)

**Comment by ariedov** [comment]
I am not sure what do you mean by 

> reset the progress when it does reload

Do you mean that you want to reset the progress and position on `reassemble`? If yes - then I am ok with it.

**Comment by raacker** [comment]
never mind. It should not move the position when axis didn't change. Then could you tell me how to move to specific position by force?

**Comment by ariedov** [comment]
There is no way to move to a specific position. For now, at least ;)

**Comment by raacker** [comment]
@ariedov oh well.....
![screenshot_20181031-204531](https://user-images.githubusercontent.com/12020398/47786085-f8ba9d80-dd4d-11e8-980c-62b66fc07ef7.png)

this is the bug that I have now :) when we change axis, it's off

**Comment by raacker** [comment]
after scrolling a few times, it gets back to normal

**Comment by ariedov** [comment]
There might be a few reasons for it.

1. The scroll offset was calculated for the vertical axis, but after we've changed it the calculation is wrong due to card size differences.
2. The progress is off, which I doubt.

**Comment by ariedov** [comment]
If everything else works, I mean if we can change card sizes, orientation and separator sizes by hot reload - I would appreciate a pull request. 
This issue can be fixed later.

**Comment by raacker** [comment]
@ariedov  let me try a bit more! I'll just make PR if I can't resolve the issue

**Comment by ariedov** [comment]
Ok, no problem. Thank you very much, I really appreciate your help.

**Comment by ariedov** [comment]
Done with that. I'll create a new issue for position storing.
